"""Backward-compatible exports for universe components.

The implementation now lives under ``market_tickers_data.universes`` while
the public API remains stable during the migration.
"""

from .universes import (
    CAC40,
    CAC40_COMPONENTS,
    DATASET,
    DATASET_ALL,
    DATASET_COMPONENTS,
    DJI,
    DJI_COMPONENTS,
    EUROSTOXX50,
    EUROSTOXX50_COMPONENTS,
    EUROSTOXX600,
    EUROSTOXX600_COMPONENTS,
    FUTURES,
    FUTURES_COMPONENTS,
    INDEX,
    INDEX_COMPONENTS,
    NASDAQ100,
    NASDAQ100_COMPONENTS,
    SBF120,
    SBF120_COMPONENTS,
    SP500,
    SP500_COMPONENTS,
    UNIVERSE_METADATA,
    WORLD_INDEX,
    WORLD_INDEX_COMPONENTS,
    get_universe_benchmark,
    get_universe_metadata,
)

__all__ = [
    'CAC40',
    'CAC40_COMPONENTS',
    'DATASET',
    'DATASET_ALL',
    'DATASET_COMPONENTS',
    'DJI',
    'DJI_COMPONENTS',
    'EUROSTOXX50',
    'EUROSTOXX50_COMPONENTS',
    'EUROSTOXX600',
    'EUROSTOXX600_COMPONENTS',
    'FUTURES',
    'FUTURES_COMPONENTS',
    'INDEX',
    'INDEX_COMPONENTS',
    'NASDAQ100',
    'NASDAQ100_COMPONENTS',
    'SBF120',
    'SBF120_COMPONENTS',
    'SP500',
    'SP500_COMPONENTS',
    'UNIVERSE_METADATA',
    'WORLD_INDEX',
    'WORLD_INDEX_COMPONENTS',
    'get_universe_benchmark',
    'get_universe_metadata',
]
